Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -65,6 +65,15 @@ jobs:
           git remote set-url origin https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/antoninfaure/node-180
           git config --unset-all http.https://github.com/.extraheader
           git add .
-          git diff-index --quiet HEAD || git commit -m 'Update content' | git push origin main
+          set +e  # Grep succeeds with nonzero exit codes to show results.
+          if git status | grep -q modified
+          then
+              set -e
+              git commit -am "content update on - $(date)"
+              git push origin main
+          else
+              set -e
+              echo "No changes since last run"
+          fi
         working-directory: 'node-repo'
 
